### ISSUE TITLE
Exception since latest SL4 changes

### ISSUE THREAD

**Issue by FichteFoll** [kaste/SublimeLinter-addon-filter#3]
```
Traceback (most recent call last):
  File "/home/fichte/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package/lint/backend.py", line 76, in <lambda>
  File "/home/fichte/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package/sublime_linter.py", line 358, in group_by_filename_and_update
  File "/home/fichte/.config/sublime-text-3/Installed Packages/SublimeLinter-addon-filter.sublime-package/plugin.py", line 61, in update_buffer_errors
TypeError: can only concatenate list (not "str") to list
```

**Comment by kaste** [comment]
Forgot to push 🙄, fixed it 4 weeks ago, sorry.

**Comment by FichteFoll** [comment]
No worries.
